#include <cmath>
#include <vector>
#include <array>
#include <string>
#include <fstream>
#include <sstream>
#include <iostream>
#include <Eigen/Core>
#include <opencv2/opencv.hpp>
#include <filesystem>